%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/maxle/Desktop/results.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/23 23:56:45

%% Initialize variables.
filename = '/home/maxle/Desktop/results.txt';
delimiter = '\t';

%% Format for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: text (%s)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
X = dataArray{:, 1};
VarName2 = dataArray{:, 2};
Y = dataArray{:, 3};
VarName4 = dataArray{:, 4};
Z = dataArray{:, 5};

%% Plotting
plot(X,Y,'xr');
hold on;
grid on;
plot(X,Z,'-b');
saveas(gcf,'series','png');


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;